artifacts_root : artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: "https://github.com/TapanKheni10/ML-Projects/raw/main/winequality.zip"
  local_data_file: artifacts/data_ingestion/winequality.zip
  unzip_dir: artifacts/data_ingestion

